[server]
bind_ip = "0.0.0.0"
bind_port = 5140
debug = false
log_dump = false

[database]
# Driver can be "sqlite", or "meilisearch"
driver = "sqlite"
batch_size = 100
batch_timeout = 5
sql_dump = false # Not applicable for Meilisearch

[web_server]
bind_ip = "0.0.0.0"
bind_port = 5141
debug = false
redact = false

[database.sqlite]
database = "syslog.sqlite3"

[database.meilisearch]
url = "http://127.0.0.1:7700"
# Set an API key if you have one configured for Meilisearch
api_key = ""
